name: Log Commit Messages on Dev

on:
  workflow_dispatch:

jobs:
  log-messages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log commit message
        run: echo "Manually triggered log on dev branch"
