name: Log Commit Messages

on:
  push:
    branches:
      - main

jobs:
  log-messages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log commit message
        run: echo "Commit message: asd"
